services:
  e-commerce:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/src
    env_file:
      - .env.development.local
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=nest-demo-postgres
      - POSTGRES_PORT=5432
    depends_on:
      - nest-demo-postgres

  nest-demo-postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data_20a:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data_20a: